[auth]
enabled = true
email.enabled = true
email.confirm = false

[database]
migrations = "migrations"

[graphql]
enabled = true
database = "postgres"  # Это правильное значение — Nhost/Hasura использует "postgres" как дефолтную БД

[functions]
enabled = true
