[auth]
enabled = true
email.enabled = true
email.confirm = false

[database]
migrations = "migrations"

[graphql]
database = "default"  # Это критично — добавь эту секцию!

[functions]
enabled = true
