[auth]
enabled = true
email.enabled = true
email.confirm = false

[database]
migrations = "migrations"

[graphql]
database = "default"  # Это ключевое поле! Без него Nhost падает

[functions]
enabled = true
