[auth]
enabled = true
email.enabled = true
email.confirm = false

[database]
migrations = "migrations"

[graphql]
enabled = true
schema = "public"  # Это правильное значение для Nhost/Hasura в 2026 году

[functions]
enabled = true
